# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Notif.me blog"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Notif.me is an open source solution to send all kinds of notifications and help you save time integrating them.<br><br><i>Built with love by developers for developers.</i>"

# Tagline near the site title
tagline: ""

# The subpath of your site, e.g. /blog, for generating urls
baseurl:

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://notifme.github.io/notifme-sdk-blog"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /2017/08/22/genesis.html
# - text: Style Guides
#   url: /style-guide/
# - text: Archives
#   url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: notifme

# Author information - author info at the bottom of the post
author_name: "Notif.me"
author_bio: "Notif.me is an open source solution to send all kinds of notifications and help you save time integrating them.<br><br><i>Built with love by developers for developers.</i>"
author_url:  "https://www.notif.me"
author_location: "France"
author_image: /images/authorimage.png

# Sidebar Add banner
# banner_url: "http://justgoodthemes.com"
# banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "notif_me"
# facebook_username: "username"
# googleplus_username: "+username"
github_username: "notifme"
# codepen_username: "username"
# dribbble_uername: "username"
medium_username: "@Notif.me"
# instagram_username: "username"
# pinterest_username: "username"
# linkedin_username: "company/username"
slack_url: "https://slackin-notifme.now.sh/"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate, jekyll-gist, jemoji]

markdown: kramdown

kramdown:
    auto_ids: false

repository: notifme/notifme-sdk-blog
